SELECT 
    da.COD_SOLICITUD AS CODIGO_SOLICITUD,
    da.COD_DOC_ADJ AS CODIGO_DOCUMENTO,
    s.NUMERO_AFILIADO,
    ts.DESCRIPCION AS TIPO_SOLICITUD,
    CASE
        WHEN ra.ACTUALIZADO_NUEVPROC = 'N' THEN ra.NOMA
        ELSE TRIM(
            TRIM(ra.PRIMER_NOMBRE || ' ' || COALESCE(ra.SEGUNDO_NOMBRE, '')) || ', ' ||
            TRIM(ra.PRIMER_APELLIDO || ' ' || COALESCE(ra.SEGUNDO_APELLIDO, '')))
    END AS NOMBRE_AFILIADO,
    CASE s.COD_RIESGO 
        WHEN 'I' THEN 'INVALIDEZ'
        WHEN 'V' THEN 'VEJEZ'
        WHEN 'S' THEN 'SOBREVIVENCIA'
        ELSE 'DESCONOCIDO'
    END AS RIESGO,
    id.DOCUMENTO AS TIPO_DOCUMENTO,
    da.FECHA_ING AS FECHA_DOCUMENTO,
    es.ESTADO_SOLICITUD,
    et.ETAPA AS ETAPA_SOLICITUD,
    UPPER(da.OBSERVACIONES) AS OBSERVACIONES,
    iid.DEPENDENCIA,
    ua.NOMBRE_CORTO_UNIDAD,
    da.NOMBRE_DOCUMENTO
FROM IVS.IVS_DOCUMENTO_ADJ da
INNER JOIN IVS.IVS_SOLICITUDES s ON da.COD_SOLICITUD = s.COD_SOLICITUD
LEFT JOIN IVS.IVS_DOCUMENTO id ON da.COD_DOCUMENTO = id.COD_DOCUMENTO
LEFT JOIN IVS.IVS_TIPO_SOLICITUD ts ON s.COD_TIPO_SOLICITUD = ts.COD_TIPO_SOLICITUD
LEFT JOIN SIGSS.RAP_AFILIADOS ra ON s.NUMERO_AFILIADO = ra.NUMERO_AFILIADO
LEFT JOIN IVS.IVS_ESTADO_SOLICITUD es ON s.ESTADO = es.COD_ESTADO_SOLICITUD
LEFT JOIN (
    SELECT it.COD_SOLICITUD, 
           MAX(it.COD_TRASLADO) KEEP (DENSE_RANK LAST ORDER BY it.FECHA_TRASLADO) AS ULTIMA_ETAPA
    FROM IVS.IVS_TRASLADO it 
    WHERE it.ESTADO NOT IN (0)
    GROUP BY it.COD_SOLICITUD
) eta ON s.COD_SOLICITUD = eta.COD_SOLICITUD
LEFT JOIN IVS.IVS_TRASLADO eta1 ON eta.ULTIMA_ETAPA = eta1.COD_TRASLADO
LEFT JOIN IVS.IVS_ETAPA et ON eta1.COD_ETAPA_DESTINO = et.COD_ETAPA
INNER JOIN IVS.IVS_PUESTO_HIST ph ON da.USUARIO_ING = ph.ID_USUARIO
INNER JOIN IVS.IVS_DEPENDENCIA iid ON ph.COD_DEPENDENCIA = iid.COD_DEPENDENCIA
INNER JOIN SPP.SPP_UNIDAD_ADMINISTRATIVA ua ON ph.COD_UNIDAD_ADMINISTRATIVA = ua.CODIGO_UNIDAD
    AND ph.ESTADO = 1
    AND ph.COD_DEPENDENCIA IN (27, 34)
WHERE da.ESTADO NOT IN (0)
AND s.ESTADO NOT IN (0)
AND s.COD_TIPO_SOLICITUD IN (18, 19)
AND da.COD_DOCUMENTO IN (32, 72, 73)
AND da.FECHA_ING >= TO_DATE('21/09/2025','DD/MM/YYYY')
AND da.FECHA_ING <= TO_DATE('27/09/2025','DD/MM/YYYY');