WITH
TRASLADOS AS (
    SELECT 
        it.COD_SOLICITUD,
        MAX(CASE WHEN it.ESTADO NOT IN (0) THEN it.COD_TRASLADO END) AS ultimo_etapa,
        MAX(CASE WHEN it.COD_ETAPA_ORIGEN IN (19, 30) AND it.COD_ETAPA_DESTINO IN (9) THEN it.COD_TRASLADO END) AS ultimo_rechazo
    FROM IVS.IVS_TRASLADO it
    GROUP BY it.COD_SOLICITUD
)
SELECT
    s.COD_SOLICITUD AS "CÓDIGO DE SOLICITUD",
    s.NUMERO_AFILIADO AS "NÚMERO DE AFILIADO",
    its.DESCRIPCION AS "TIPO DE SOLICITUD",
    DECODE(s.EXPEDIENTE_ELECTRONICO, '0', 'NO', '1', 'SI') AS "EXPEDIENTE ELECTRONICO",
    s.FECHA_RECEPCION AS "FECHA DE SOLICITUD",
    DECODE(s.COD_RIESGO, 'I', 'INVALIDEZ', 'V', 'VEJEZ', 'S', 'SOBREVIVENCIA') AS "RIESGO",
    CASE
        WHEN ra.ACTUALIZADO_NUEVPROC = 'N' THEN TO_CHAR(ra.NOMA)
        ELSE TRIM(ra.primer_nombre || ' ' || ra.segundo_nombre) || ', ' || TRIM(ra.primer_apellido || ' ' || ra.segundo_apellido)
    END AS "NOMBRE AFILIADO",
    DECODE(ra.SEXO_AFILIADO, 'M', 'MASCULINO', 'F', 'FEMENINO') AS "GÉNERO DE AFILIADO",
    ra.FECHA_NACIMIENTO AS "FECHA DE NACIMIENTO",
    ua.NOMBRE_CORTO_UNIDAD AS "UNIDAD ADMINISTRATIVA",
    dcd.NOMBRE_DEPARTAMENTO AS "DEPARTAMENTO DE RESIDENCIA",
    cmm.NOMBRE_MUNICIPIO AS "MUNICIPIO DE RESIDENCIA",
    irec.FECHA_ING AS "FECHA ULTIMO RECHAZO",
    su.PRIMER_NOMBRE || DECODE(su.SEGUNDO_NOMBRE,NULL,' ',' ' || su.SEGUNDO_NOMBRE || ' ') || su.PRIMER_APELLIDO || DECODE(su.SEGUNDO_APELLIDO,NULL,'',' ' || su.SEGUNDO_APELLIDO) AS "USUARIO RECEPCIONÓ RECHAZO", 
    es.ESTADO_SOLICITUD AS "ESTADO SOLICITUD",
    et.ETAPA AS "ETAPA SOLICITUD",
    UPPER(irec.OBSERVACIONES) AS "OBSERVACIONES RECHAZO"
FROM IVS.IVS_SOLICITUDES s
LEFT JOIN IVS.IVS_TIPO_SOLICITUD its ON s.COD_TIPO_SOLICITUD = its.COD_TIPO_SOLICITUD
LEFT JOIN IVS.IVS_CALCULO_RESULTADO icr ON s.COD_SOLICITUD = icr.COD_SOLICITUD
LEFT JOIN TRASLADOS t ON s.COD_SOLICITUD = t.COD_SOLICITUD
LEFT JOIN IVS.IVS_TRASLADO eta1 ON t.ultimo_etapa = eta1.COD_TRASLADO
LEFT JOIN IVS.IVS_TRASLADO irec ON t.ultimo_rechazo = irec.COD_TRASLADO
LEFT JOIN IVS.IVS_ESTADO_SOLICITUD es ON s.ESTADO = es.COD_ESTADO_SOLICITUD
LEFT JOIN IVS.IVS_ETAPA et ON eta1.COD_ETAPA_DESTINO = et.COD_ETAPA
LEFT JOIN SIGSS.RAP_AFILIADOS ra ON s.NUMERO_AFILIADO = ra.NUMERO_AFILIADO
LEFT JOIN SPP.SPP_UNIDAD_ADMINISTRATIVA ua ON s.COD_UNIDAD_ADMINISTRATIVA = ua.CODIGO_UNIDAD
LEFT JOIN SIGSS.CCL_MUNICIPIOS cmm ON s.COD_DEPTO_RESIDENCIA = cmm.CODIGO_DEPARTAMENTO AND s.COD_MUNI_RESIDENCIA = cmm.CODIGO_MUNICIPIO
LEFT JOIN SIGSS.CCL_DEPARTAMENTOS dcd ON s.COD_DEPTO_RESIDENCIA = dcd.CODIGO_DEPARTAMENTO
LEFT JOIN SPP.SPP_USUARIO su ON irec.USR_RECEPCION = su.ID_USUARIO
WHERE s.ESTADO NOT IN (0)
AND s.COD_TIPO_SOLICITUD NOT IN (32, 31, 30, 29) 
AND TRUNC(irec.FECHA_ING) BETWEEN TO_DATE('21/09/2025','DD/MM/YYYY') AND TO_DATE('27/09/2025','DD/MM/YYYY');