SELECT
sc.COD_CASO AS "CÓDIGO DE CASO",
sc.NUMERO_AFILIADO AS "NÚMERO DE AFILIADO",
ra.PRIMER_APELLIDO || decode(ra.SEGUNDO_APELLIDO,null, ', ', ' ' || ra.SEGUNDO_APELLIDO || ', ') || ra.PRIMER_NOMBRE || decode(ra.SEGUNDO_NOMBRE, null, '', ' ' || ra.SEGUNDO_NOMBRE) AS "NOMBRE AFILIADO",
DECODE(sc.ID_RIESGO, 'V', 'VEJEZ', 'I', 'INVALIDEZ', 'C', 'CONTRIBUCIÓN VOLUNTARIA','S', 'SOBREVIVENCIA', 'N/A') AS RIESGO,
    CASE
        WHEN sc.COD_FUENTE = 3 THEN 'SOLICITUD MANUAL'
        WHEN sc.COD_FUENTE = 5 THEN 'SOLICITUD DE INTERESADO'
        WHEN sc.COD_FUENTE = 6 THEN sct.TIPO_SOLICITUD
        WHEN sc.COD_FUENTE = 7 THEN its.TIPO_SOLICITUD
    END AS "TIPO DE SOLICITUD",
ua.NOMBRE_CORTO_UNIDAD AS "UNIDAD EMISORA REQUERIMIENTO",
    CASE
        WHEN sc.COD_FUENTE = 3 THEN sd1.DEPENDENCIA
        WHEN sc.COD_FUENTE = 5 THEN sd1.DEPENDENCIA
        WHEN sc.COD_FUENTE = 6 THEN sd1.DEPENDENCIA
        WHEN sc.COD_FUENTE = 7 THEN sdv.DEPENDENCIA
    END AS "DEPENDENCIA EMISORA",
CASE
        WHEN sc.COD_FUENTE = 3 THEN sc.NUMERO_DOCUMENTO
        WHEN sc.COD_FUENTE = 5 THEN sc.COD_REQUERIMIENTO_INT
        WHEN sc.COD_FUENTE = 6 THEN sc.COD_REQUERIMIENTO_SICV
        WHEN sc.COD_FUENTE = 7 THEN sc.COD_REQUERIMIENTO_SIIVS
    END AS "CÓDIGO REQUERIMIENTO",
sc.FECHA_DOCUMENTO AS "FECHA DOCUMENTO",
sf.FUENTE,
DECODE(hpi.COD_TURNO, '1', 'AM', '2', 'PM', '3', 'FDS') AS "TURNO DEL INVESTIGADOR",
UPPER(hpi.NOMBRE_REPORTE) AS "NOMBRE INVESTIGADOR",
fti.FECHA_ING AS "FECHA TRASLADO INVESTIGADOR",
UPPER(hpr.NOMBRE_REPORTE) AS "NOMBRE REVISOR",
ftr.FECHA_ING AS "FECHA TRASLADO REVISOR",
UPPER(hps.NOMBRE_REPORTE) AS "NOMBRE SUPERVISOR",
fts.FECHA_ING AS "FECHA TRASLADO SUPERVISOR",
ftd.FECHA_ING AS "FECHA DESPACHO",
ec.ESTADO_CASO AS "ESTADO",
et.ETAPA AS "ETAPA",
si.NUMERO_PATRONO AS "NÚMERO PATRONAL",
rp.NOMBRE_RAZON_SOCIAL AS "NOMBRE PATRONO",
'''' || si.MES_INICIO || '-' || si.ANIO_INICIO AS FECHA_INICIO,
'''' || si.MES_FIN || '-' || si.ANIO_FIN AS FECHA_FIN
FROM SIHIS.SIHIS_CASO sc
LEFT JOIN SPP.SPP_DEPENDENCIA sd1 ON sc.COD_DEPENDENCIA = sd1.COD_DEPENDENCIA
LEFT JOIN SIHIS.SIHIS_FUENTE sf ON sc.COD_FUENTE = sf.COD_FUENTE
LEFT JOIN SIHIS.SIHIS_ESTADO_CASO ec ON sc.ESTADO = ec.COD_ESTADO_CASO
LEFT JOIN SIHIS.SIHIS_HIST_PUESTO hpi ON sc.COD_INVESTIGADOR = hpi.SEQ_HIST_PUESTO
LEFT JOIN SIHIS.SIHIS_HIST_PUESTO hpr ON sc.COD_REVISOR = hpr.SEQ_HIST_PUESTO
LEFT JOIN SIHIS.SIHIS_HIST_PUESTO hps ON sc.COD_SUPERVISOR = hps.SEQ_HIST_PUESTO
LEFT JOIN IVS.IVS_REQUERIMIENTOS ir ON sc.COD_REQUERIMIENTO_SIIVS = ir.COD_REQUERIMIENTO
LEFT JOIN IVS.IVS_SOLICITUDES ivs ON ir.COD_SOLICITUD = ivs.COD_SOLICITUD
LEFT JOIN IVS.IVS_TIPO_SOLICITUD its ON ivs.COD_TIPO_SOLICITUD = its.COD_TIPO_SOLICITUD
LEFT JOIN SICV.CV_REQUERIMIENTO scr ON sc.COD_REQUERIMIENTO_SICV = scr.COD_REQUERIMIENTO
LEFT JOIN SICV.CV_SOLICITUD scs ON scr.COD_SOLICITUD = scs.COD_SOLICITUD
LEFT JOIN SICV.CV_TIPO_SOLICITUD sct ON scs.COD_TIPO_SOLICITUD = sct.COD_TIPO_SOLICITUD
LEFT JOIN SIHIS.SIHIS_INGRESO si ON sc.COD_CASO = si.COD_CASO
LEFT JOIN SIGSS.RAP_PATRONOS rp ON si.NUMERO_PATRONO = rp.NUMERO_PATRONO
LEFT JOIN IVS.IVS_DEPENDENCIA sdv ON ir.COD_DEPENDENCIA_EMISORA = sdv.COD_DEPENDENCIA
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_DESTINO = 3
        GROUP BY COD_CASO
    ) fti ON sc.COD_CASO = fti.COD_CASO
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_DESTINO = 5
        GROUP BY COD_CASO
    ) ftr ON sc.COD_CASO = ftr.COD_CASO
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_DESTINO = 6
        GROUP BY COD_CASO
    ) fts ON sc.COD_CASO = fts.COD_CASO
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_DESTINO = 8
        GROUP BY COD_CASO
    ) ftd ON sc.COD_CASO = ftd.COD_CASO
LEFT JOIN (
        SELECT DISTINCT sh.COD_CASO, MAX(sh.COD_TRASLADO) OVER (PARTITION BY sh.COD_CASO ORDER BY sh.COD_CASO) ULTIMA_ETAPA
        FROM SIHIS.SIHIS_TRASLADO sh) eta
        ON sC.COD_CASO = eta.COD_CASO
        LEFT JOIN SIHIS.SIHIS_TRASLADO eta1
        ON eta.ULTIMA_ETAPA = eta1.COD_TRASLADO
LEFT JOIN SIHIS.SIHIS_ETAPA et ON eta1.COD_ETAPA_DESTINO = et.COD_ETAPA
LEFT JOIN SPP.SPP_UNIDAD_ADMINISTRATIVA ua ON sc.COD_UNIDAD_ADMINISTRATIVA = ua.CODIGO_UNIDAD
LEFT JOIN SIGSS.RAP_AFILIADOS ra ON sc.NUMERO_AFILIADO = ra.NUMERO_AFILIADO
WHERE sc.ESTADO NOT IN (0)
AND si.ESTADO != 0
ORDER BY sc.COD_CASO DESC, si.ANIO_INICIO ASC;