SELECT
    sc.COD_CASO AS "CÓDIGO DE CASO",
    sc.NUMERO_AFILIADO AS "NÚMERO DE AFILIADO",
    CASE
        WHEN ra.ACTUALIZADO_NUEVPROC = 'N' THEN NOMA
        ELSE ra.PRIMER_APELLIDO || decode(ra.SEGUNDO_APELLIDO,null, ', ', ' ' || ra.SEGUNDO_APELLIDO || ', ') || ra.PRIMER_NOMBRE || decode(ra.SEGUNDO_NOMBRE, null, '', ' ' || ra.SEGUNDO_NOMBRE) 
    END AS "NOMBRE AFILIADO",
    DECODE(sc.ID_RIESGO, 'V', 'VEJEZ', 'I', 'INVALIDEZ', 'C', 'CONTRIBUCIÓN VOLUNTARIA','S', 'SOBREVIVENCIA', 'N/A') AS RIESGO,
    COALESCE(
        CASE
            WHEN sc.COD_FUENTE = 3 THEN 'SOLICITUD MANUAL'
            WHEN sc.COD_FUENTE = 5 THEN 'SOLICITUD DE INTERESADO'
            WHEN sc.COD_FUENTE = 6 THEN sct.TIPO_SOLICITUD
            WHEN sc.COD_FUENTE = 7 THEN its.TIPO_SOLICITUD
        END, 'SOLICITUD MANUAL') AS "TIPO DE SOLICITUD",
    CASE
        WHEN sc.COD_FUENTE = 3 THEN NULL
        WHEN sc.COD_FUENTE = 5 THEN NULL
        WHEN sc.COD_FUENTE = 6 THEN scs.COD_SOLICITUD
        WHEN sc.COD_FUENTE = 7 THEN ivs.COD_SOLICITUD
    END AS "CÓDIGO SOLICITUD SIIVS-SICV",
    CASE
        WHEN sc.COD_FUENTE = 3 THEN NULL
        WHEN sc.COD_FUENTE = 5 THEN NULL
        WHEN sc.COD_FUENTE = 6 THEN scs.FECHA_RECEPCION
        WHEN sc.COD_FUENTE = 7 THEN ivs.FECHA_RECEPCION
    END AS "FECHA_SOLICITUD",
    DECODE(ua.NOMBRE_CORTO_UNIDAD, 'DEPARTAMENTO DE INVALIDEZ VEJEZ Y SOBREVIVENCIA', 'CENTRO DE ATENCIÓN AL AFILIADO -CATAFI-', ua.NOMBRE_CORTO_UNIDAD) AS "UNIDAD EMISORA REQUERIMIENTO",
    CASE
        WHEN sc.COD_FUENTE IN (3, 5, 6) THEN sd1.DEPENDENCIA
        WHEN sc.COD_FUENTE = 7 THEN sdv.DEPENDENCIA
    END AS "DEPENDENCIA EMISORA",
    CASE
        WHEN sc.COD_FUENTE = 3 THEN sc.NUMERO_DOCUMENTO
        WHEN sc.COD_FUENTE = 5 THEN sc.COD_REQUERIMIENTO_INT
        WHEN sc.COD_FUENTE = 6 THEN sc.COD_REQUERIMIENTO_SICV
        WHEN sc.COD_FUENTE = 7 THEN sc.COD_REQUERIMIENTO_SIIVS
    END AS "CÓDIGO REQUERIMIENTO",
    CASE
        WHEN sc.COD_FUENTE IN (1, 2, 3, 4, 5) THEN sc.FECHA_ING
        WHEN sc.COD_FUENTE IN (6, 7) THEN sc.FECHA_DOCUMENTO
    END AS "FECHA DOCUMENTO",
    sf.FUENTE,
    ftc.FECHA_ING AS "FECHA TRASLADO RECEPCIÓN",
    fta.FECHA_ING AS "FECHA TRASLADO ARCHIVO",
    DECODE(hpi.COD_TURNO, '1', 'AM', '2', 'PM', '3', 'FDS') AS "TURNO DEL INVESTIGADOR",
    hpi.COD_OPERADOR AS "CÓDIGO DE OPERADOR",
    UPPER(hpi.NOMBRE_REPORTE) AS "NOMBRE INVESTIGADOR",
    fti.FECHA_ING AS "FECHA TRASLADO INVESTIGADOR",
    UPPER(hpr.NOMBRE_REPORTE) AS "NOMBRE REVISOR",
    ftr.FECHA_ING AS "FECHA TRASLADO REVISOR",
    UPPER(hps.NOMBRE_REPORTE) AS "NOMBRE SUPERVISOR",
    fts.FECHA_ING AS "FECHA TRASLADO SUPERVISOR",
    ftd.FECHA_ING AS "FECHA DESPACHO",
    NVL(rechazos.TOTAL_RECHAZOS, 0) AS "CANTIDAD CORRECIONES",
    ing.INGRESOS AS "INGRESOS POR CASO",
    (SELECT COUNT(sai.MES_APORTE) 
        FROM SIHIS.SIHIS_APORTE_INFORME sai
        LEFT JOIN SIHIS.SIHIS_INGRESO si ON sai.COD_INGRESO = si.COD_INGRESO
        WHERE sai.COD_INGRESO = si.COD_INGRESO 
        AND sai.MES_APORTE IS NOT NULL
        AND si.COD_CASO = sc.COD_CASO
    ) AS "TOTAL DE CUOTAS",
    ec.ESTADO_CASO AS "ESTADO",
    et.ETAPA AS "ETAPA"
FROM SIHIS.SIHIS_CASO sc
LEFT JOIN SPP.SPP_DEPENDENCIA sd1 ON sc.COD_DEPENDENCIA = sd1.COD_DEPENDENCIA
LEFT JOIN SIHIS.SIHIS_FUENTE sf ON sc.COD_FUENTE = sf.COD_FUENTE
LEFT JOIN SIHIS.SIHIS_ESTADO_CASO ec ON sc.ESTADO = ec.COD_ESTADO_CASO
LEFT JOIN SIHIS.SIHIS_HIST_PUESTO hpi ON sc.COD_INVESTIGADOR = hpi.SEQ_HIST_PUESTO
LEFT JOIN SIHIS.SIHIS_HIST_PUESTO hpr ON sc.COD_REVISOR = hpr.SEQ_HIST_PUESTO
LEFT JOIN SIHIS.SIHIS_HIST_PUESTO hps ON sc.COD_SUPERVISOR = hps.SEQ_HIST_PUESTO
LEFT JOIN IVS.IVS_REQUERIMIENTOS ir ON sc.COD_REQUERIMIENTO_SIIVS = ir.COD_REQUERIMIENTO
LEFT JOIN IVS.IVS_SOLICITUDES ivs ON ir.COD_SOLICITUD = ivs.COD_SOLICITUD
LEFT JOIN IVS.IVS_TIPO_SOLICITUD its ON ivs.COD_TIPO_SOLICITUD = its.COD_TIPO_SOLICITUD
LEFT JOIN SICV.CV_REQUERIMIENTO scr ON sc.COD_REQUERIMIENTO_SICV = scr.COD_REQUERIMIENTO
LEFT JOIN SICV.CV_SOLICITUD scs ON scr.COD_SOLICITUD = scs.COD_SOLICITUD
LEFT JOIN SICV.CV_TIPO_SOLICITUD sct ON scs.COD_TIPO_SOLICITUD = sct.COD_TIPO_SOLICITUD
LEFT JOIN IVS.IVS_DEPENDENCIA sdv ON ir.COD_DEPENDENCIA_EMISORA = sdv.COD_DEPENDENCIA
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_ORIGEN = 1 AND COD_ETAPA_DESTINO = 2 AND ESTADO <> 0
        GROUP BY COD_CASO
    ) ftc ON sc.COD_CASO = ftc.COD_CASO
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_ORIGEN = 2 AND COD_ETAPA_DESTINO = 13 AND ESTADO <> 0
        GROUP BY COD_CASO
    ) fta ON sc.COD_CASO = fta.COD_CASO
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_ORIGEN = 13 AND COD_ETAPA_DESTINO = 3 AND ESTADO <> 0
        GROUP BY COD_CASO
    ) fti ON sc.COD_CASO = fti.COD_CASO
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_ORIGEN = 3 AND COD_ETAPA_DESTINO = 5 AND ESTADO <> 0
        GROUP BY COD_CASO
    ) ftr ON sc.COD_CASO = ftr.COD_CASO
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE COD_ETAPA_ORIGEN = 5 AND COD_ETAPA_DESTINO = 6 AND ESTADO <> 0
        GROUP BY COD_CASO
    ) fts ON sc.COD_CASO = fts.COD_CASO
LEFT JOIN (
        SELECT COD_CASO, MAX(FECHA_ING) AS FECHA_ING
        FROM SIHIS.SIHIS_TRASLADO
        WHERE (COD_ETAPA_ORIGEN = 6 OR COD_ETAPA_ORIGEN = 7) AND COD_ETAPA_DESTINO = 8 AND ESTADO <> 0
        GROUP BY COD_CASO
    ) ftd ON sc.COD_CASO = ftd.COD_CASO
LEFT JOIN (
        SELECT DISTINCT sh.COD_CASO, MAX(sh.COD_TRASLADO) OVER (PARTITION BY sh.COD_CASO ORDER BY sh.COD_CASO) ULTIMA_ETAPA
        FROM SIHIS.SIHIS_TRASLADO sh
        WHERE sh.ESTADO <> 0) eta
        ON sC.COD_CASO = eta.COD_CASO
        LEFT JOIN SIHIS.SIHIS_TRASLADO eta1
        ON eta.ULTIMA_ETAPA = eta1.COD_TRASLADO
LEFT JOIN SIHIS.SIHIS_ETAPA et ON eta1.COD_ETAPA_DESTINO = et.COD_ETAPA
LEFT JOIN (
        SELECT COD_CASO, COUNT(1) INGRESOS
        FROM SIHIS.SIHIS_INGRESO
        WHERE ESTADO = 1
        GROUP BY COD_CASO
    ) ing ON sc.COD_CASO = ing.COD_CASO
LEFT JOIN (
    SELECT
        retorno.COD_CASO,
        COUNT(1) AS TOTAL_RECHAZOS
    FROM
        SIHIS.SIHIS_TRASLADO retorno
    WHERE
        retorno.COD_ETAPA_ORIGEN = 5 AND retorno.COD_ETAPA_DESTINO = 3
        AND retorno.ESTADO <> 0
        AND EXISTS (
            SELECT 1
            FROM SIHIS.SIHIS_TRASLADO envio
            WHERE
                envio.COD_CASO = retorno.COD_CASO
                AND envio.USUARIO_ING = retorno.USR_RECEPCION
                AND envio.COD_ETAPA_ORIGEN = 3 AND envio.COD_ETAPA_DESTINO = 5
                AND envio.ESTADO <> 0
        )
    GROUP BY
        retorno.COD_CASO
) rechazos ON sc.COD_CASO = rechazos.COD_CASO
LEFT JOIN SPP.SPP_UNIDAD_ADMINISTRATIVA ua ON sc.COD_UNIDAD_ADMINISTRATIVA = ua.CODIGO_UNIDAD
LEFT JOIN SIGSS.RAP_AFILIADOS ra ON sc.NUMERO_AFILIADO = ra.NUMERO_AFILIADO
WHERE sc.ESTADO NOT IN (0, 20)
AND TRUNC(ftd.FECHA_ING) BETWEEN TO_DATE('01/01/2025','DD/MM/YYYY') AND TO_DATE('31/12/2025','DD/MM/YYYY');