WITH
  FECHAS_SIHIS_PIVOT AS (
     SELECT
       st.COD_REQUERIMIENTO,
       MIN(
         CASE
           WHEN st.COD_ETAPA_ORIGEN = 16 AND st.COD_ETAPA_DESTINO = 11
           THEN st.COD_TRASLADO
         END
       ) AS COD_TRASLADO_SIPA,
       MAX(st.COD_TRASLADO) AS ULTIMO_COD_TRASLADO
     FROM SIHIS.SIHIS_TRASLADO_REQ st
     WHERE
       st.ESTADO <> 0
     GROUP BY
       st.COD_REQUERIMIENTO
   ),
  FECHAS_SIPA_PIVOT AS (
     SELECT
       st.COD_SOLICITUD,
       MIN(
         CASE
           WHEN st.COD_ETAPA_ORIGEN = 1 AND st.COD_ETAPA_DESTINO = 2
           THEN st.FECHA_ING
         END
       ) AS FECHA_RECEPCION,
       MIN(
         CASE
           WHEN st.COD_ETAPA_ORIGEN = 2 AND st.COD_ETAPA_DESTINO = 4
           THEN st.FECHA_ING
         END
       ) AS FECHA_INSPECCION,
       MAX(
         CASE
           WHEN st.COD_ETAPA_ORIGEN = 4 AND st.COD_ETAPA_DESTINO = 6
           THEN st.FECHA_ING
         END
       ) AS FECHA_REVISION,
       MAX(
         CASE
           WHEN st.COD_ETAPA_ORIGEN = 6 AND st.COD_ETAPA_DESTINO = 7
           THEN st.FECHA_ING
         END
       ) AS FECHA_VISTO_BUENO,
       MAX(
         CASE
           WHEN st.COD_ETAPA_ORIGEN = 7 AND st.COD_ETAPA_DESTINO = 9
           THEN st.FECHA_ING
         END
       ) AS FECHA_FINALIZACION,
       MAX(st.COD_TRASLADO) KEEP (DENSE_RANK LAST ORDER BY st.FECHA_ING, st.COD_TRASLADO) AS ULTIMO_COD_TRASLADO_SIPA
     FROM SIPA.SIPA_TRASLADO st
     WHERE
       st.ESTADO <> 0
     GROUP BY
       st.COD_SOLICITUD
   )
SELECT
  r.COD_CASO,
  r.COD_REQUERIMIENTO,
  r.NUMERO_AFILIADO,
  r.NUMERO_PATRONO,
  rp.NOMPAT AS "NOMBRE PATRONO",
  rp.NOMEMP AS "NOMBRE EMPRESA",
  d.NOMBRE_DEPARTAMENTO AS "DEPARTAMENTO EMPRESA",
  m.NOMBRE_MUNICIPIO AS "MUNICIPIO DE EMPRESA",
  r.ANIO_INGRESO,
  r.NUMERO_INGRESO,
  su.PRIMER_NOMBRE || ' ' || su.PRIMER_APELLIDO AS "USUARIO CREÓ REGISTRO",
  ds.DEPENDENCIA AS "DEPENDENCIA REQUIRENTE",
  dd.DEPENDENCIA AS "DEPENDENCIA DESTINO",
  CASE r.ID_RIESGO
    WHEN 'I' THEN 'INVALIDEZ'
    WHEN 'V' THEN 'VEJEZ'
    WHEN 'S' THEN 'SOBREVIVENCIA'
  END AS RIESGO,
  de.NOMBRE_DOCUMENTO,
  r.FECHA_SOLICITUD,
  dr.DEPENDENCIA AS "DEPENDENCIA SOLICITANTE",
  id.DEPENDENCIA AS "DEPENDENCIA I.V.S.",
  r.NUMERO_OFICIO_REF,
  s.SISTEMA AS "SISTEMA DESTINO",
  r.COD_SOLICITUD_SIPA,
  ft_sihis.FECHA_ING AS "FECHA TRASLADO SIPA",
  fsp.FECHA_RECEPCION AS "FECHA RECEPCIÓN",
  fsp.FECHA_INSPECCION AS "FECHA INSPECCIÓN",
  ua.NOMBRE_CORTO_UNIDAD AS "UNIDAD INSPECTORA ASIGNADA",
  fsp.FECHA_REVISION AS "FECHA REVISIÓN",
  fsp.FECHA_VISTO_BUENO AS "FECHA VISTO BUENO",
  fsp.FECHA_FINALIZACION AS "FECHA FINALIZACIÓN",
  r.FECHA_RESPUESTA AS "FECHA ENVIO RESPUESTA",
  r.FECHA_RECEPCION_RES AS "FECHA RECEPCIÓN RESPUESTA",
  se.ETAPA AS "ETAPA SIPA",
  er.ESTADO_REQUERIMIENTO AS "ESTADO REQUERIMIENTO SIHIS"
FROM SIHIS.SIHIS_REQUERIMIENTO r
  LEFT JOIN SIHIS.SIHIS_ESTADO_REQUERIMIENTO er ON r.ESTADO = er.COD_ESTADO_REQUERIMIENTO
  LEFT JOIN SIGSS.RAP_PATRONOS rp ON r.NUMERO_PATRONO = rp.NUMERO_PATRONO
  LEFT JOIN SIGSS.CCL_DEPARTAMENTOS d ON rp.DEPARTAMENTO_PATRONO = d.CODIGO_DEPARTAMENTO
  LEFT JOIN SIGSS.CCL_MUNICIPIOS m ON rp.DEPARTAMENTO_PATRONO = m.CODIGO_DEPARTAMENTO AND rp.MUNICIPIO_PATRONO = m.CODIGO_MUNICIPIO
  LEFT JOIN SPP.SPP_DEPENDENCIA ds ON r.COD_DEPENDENCIA_SOL = ds.COD_DEPENDENCIA
  LEFT JOIN SPP.SPP_DEPENDENCIA dd ON r.COD_DEPENDENCIA_DESTINO = dd.COD_DEPENDENCIA
  LEFT JOIN SPP.SPP_DEPENDENCIA dr ON r.COD_DEPENDENCIA_REF = dr.COD_DEPENDENCIA
  LEFT JOIN IVS.IVS_DEPENDENCIA id ON r.COD_DEPENDENCIA_IVS = id.COD_DEPENDENCIA
  LEFT JOIN SPP.SPP_DOCUMENTO_EXP de ON r.COD_DOC_EXP = de.COD_DOC_EXP
  LEFT JOIN SPP.SPP_SISTEMA s ON r.COD_SISTEMA = s.COD_SISTEMA
  LEFT JOIN SPP.SPP_USUARIO su ON r.USUARIO_ING = su.ID_USUARIO
  LEFT JOIN SIPA.SIPA_SOLICITUD sp ON r.COD_REQUERIMIENTO = sp.COD_REQUERIMIENTO_SIHIS
  LEFT JOIN SPP.SPP_UNIDAD_ADMINISTRATIVA ua ON sp.COD_UNIDAD_INSPECTORA = ua.CODIGO_UNIDAD
  LEFT JOIN FECHAS_SIHIS_PIVOT fhp ON r.COD_REQUERIMIENTO = fhp.COD_REQUERIMIENTO
  LEFT JOIN SIHIS.SIHIS_TRASLADO_REQ ft_sihis ON fhp.COD_TRASLADO_SIPA = ft_sihis.COD_TRASLADO
  LEFT JOIN FECHAS_SIPA_PIVOT fsp ON sp.COD_SOLICITUD = fsp.COD_SOLICITUD
  LEFT JOIN SIPA.SIPA_TRASLADO st_sipa ON fsp.ULTIMO_COD_TRASLADO_SIPA = st_sipa.COD_TRASLADO
  LEFT JOIN SIPA.SIPA_ETAPA se ON st_sipa.COD_ETAPA_DESTINO = se.COD_ETAPA
WHERE
  r.ESTADO <> 0